Update package dependencies, fix vulnerabilities, and remove pify
body-builder/typescript-cp pull request #12
Opened 2023-04-25 21:51 UTC by billyzkid

This PR addresses issue https://github.com/body-builder/typescript-cp/issues/11.

1. Updates all package dependencies to their latest versions (to fix all listed vulnerabilities)
2. Updates `typescript` which was listed as a v4.x peer dependency (preventing it from being installed for packages that depend on the latest version of TypeScript v5.x)
3. Removes the `pify` dependency in favor of using built-in promise functionality in `rimraf`, `fs`, and `fs-extras`, etc.

Note this now installs and builds for me without any issues, but is basically untested since a) I am on Windows, and b) I am not familiar with testing binaries built from a local package/repository.

2023-05-02 11:17 UTC, bencergazda requested changes
Thanks for your work! It goes on the right direction, but I still need some minor changes.

2023-05-02 11:17 UTC, bencergazda commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
The async/await should be kept. This ensures the possibility of having asynchronous loaders.

2023-05-02 11:17 UTC, bencergazda commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
Regarding `Buffer` instead of `string`, I think that it should be changed only in a separate feature, with a similar functionality as [webpack's "Raw" Loader](https://v4.webpack.js.org/api/loaders/#raw-loader).

2023-05-02 11:17 UTC, bencergazda commented on src/helpers.ts
> +	const processed_content = apply_loaders(raw_content, source_path, destination_path, config);
await should be kept here, as further below

2023-05-03 00:46 UTC, billyzkid commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
VSCode was showing me a warning that `await` had no effect on the expression below, but I get it now.

2023-05-03 00:49 UTC, billyzkid commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
Ok, the IDE was showing me a return value of `Buffer` so I thought it was due to the package updates.

2023-05-03 00:54 UTC, billyzkid commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
Actually, it does look like the fse package update now requires an encoding if you want `raw_content` to be a `string` vs. a `Buffer`.

I'll change it to this so we can keep it a string unless you have a better idea.

```
const raw_content = await fse.readFile(source_path, "utf-8");
```

2023-05-03 01:43 UTC, billyzkid commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
I tested it more thoroughly and it does need to use a `Buffer` otherwise it fails to read and copy binary files properly.

2023-05-03 22:15 UTC, bencergazda commented on package.json
> +    "typescript": "^5.0.4"
">=4.2.3" will be ok now for peerDependencies, but please keep "^5.0.4" in devDependencies!

2023-05-03 22:21 UTC, bencergazda commented on src/helpers.ts
> + * Passes the content of the source file to each loader in sequence and returns the final content
```suggestion
 * Passes the content of the source file to each loader in sequence and returns a Promise with the final content
```

2023-05-03 22:22 UTC, bencergazda commented on package.json
> +    "typescript": ">=4.2.3"
```suggestion
    "typescript": "^5.0.4"
```

2023-05-03 22:23 UTC, bencergazda approved these changes

2023-05-03 22:32 UTC, bencergazda commented on src/helpers.ts
> +function apply_loaders(raw_content: Buffer, source_path: string, destination_path: string, config: Config): Buffer {
I'm afraid we did not use `@types/fs-extra` earlier :-)

2023-05-04 18:05 UTC, merged

2023-05-07 12:00 UTC, bencergazda commented
Landed in 0.1.8, thanks for the contribution!